"""Add Colunas Cliente

Revision ID: a7f963aa32da
Revises: 3355d64ab742
Create Date: 2020-07-26 22:26:14.882934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f963aa32da'
down_revision = '3355d64ab742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('celular', sa.String(length=14), nullable=True))
    op.add_column('cliente', sa.Column('cpf', sa.String(length=11), nullable=False))
    op.add_column('cliente', sa.Column('data_atualizacao', sa.DateTime(), nullable=True))
    op.add_column('cliente', sa.Column('data_criacao', sa.DateTime(), nullable=True))
    op.add_column('cliente', sa.Column('data_nascimento', sa.DateTime(), nullable=True))
    op.add_column('cliente', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'cliente', ['cpf'])
    op.create_unique_constraint(None, 'cliente', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cliente', type_='unique')
    op.drop_constraint(None, 'cliente', type_='unique')
    op.drop_column('cliente', 'email')
    op.drop_column('cliente', 'data_nascimento')
    op.drop_column('cliente', 'data_criacao')
    op.drop_column('cliente', 'data_atualizacao')
    op.drop_column('cliente', 'cpf')
    op.drop_column('cliente', 'celular')
    # ### end Alembic commands ###
